version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Lint Dockerfile
          command: docker run --rm --interactive hadolint/hadolint < Dockerfile

  test-app:
    docker:
      - image: golang:latest
    steps:
      - checkout
      - run:
          name: Test Go App
          command: |
            go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Docker Image
          command: ./build_push_image_karsajobs.sh

  build-app-karsajobs-ui:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Docker Image
          command: ./build_push_image_karsajobs_ui.sh

workflows:
  build:
    jobs:
      - lint-dockerfile:
          filters:
            branches:
              only:
                - karsajobs
                - karsajobs-ui
      - test-app:
          filters:
            branches:
              only: karsajobs
      - build-app-karsajobs:
          filters:
            branches:
              only: karsajobs
      - build-app-karsajobs-ui:
          filters:
            branches:
              only: karsajobs-ui
